### ISSUE TITLE
Replacing kdesu with pkexec for other linuxes

### ISSUE THREAD

**Issue by kamilsokolowski** [p4p1/havoc-ligolo#1]
During installation i have problems with using kdesu on Kali Linux. For next version it would be great to change kdesu for pkexec which is more modern.

**Comment by p4p1** [comment]
Sounds good ill change this once im on my laptop 👌 thanks didnt know about pkexec

**Comment by p4p1** [comment]
So I changed out the kdesu section with pkexec and I tried out manually on a ubuntu live machine just to see if the syntax was correct with pkexec since my home machine only works with pkexec through the terminal and not with the GUI prompt like gnome does it. I'll try it out on kali linux once I have a bit more time. If you have time to test it out and realize it's not working you can just notify me and I'll check more in depth.

**Comment by kamilsokolowski** [comment]
Sure, i was trying pkexec on xfce based distros. I look in to it on some gnome interfaces. Probably it will be required to made some conditions based on OS.

**Comment by kamilsokolowski** [comment]
Tested on Ubuntu 22.04 with GNOME GUI.
Here is my fix, there was issu with running commands, pkexec doesn't need to have command wraped in double quotes. Also in command u need to specify as which user you want to run(-u). I am posting paste with my solution below.
https://pastebin.com/bXrygkM7
![image](https://github.com/p4p1/havoc-ligolo/assets/16105665/56b8700a-3db4-4c74-ad8d-c9111baf6aa5)

**Comment by p4p1** [comment]
Nice one man thank you I'll reopen and close this once it's merged with main and fully working. Also wouldn't you need to know the root password when you do pkexec -u root? wouldn't that break in cases where the root password is different from a user that has sudo access?

**Comment by kamilsokolowski** [comment]
In most cases i think it shouldn't be a problem beacuse in ubuntu, kali linux root passworrd is same as first user password. Only exception is with non standard system setup or Fedora/CentOs/RHEL where you set up root password separately.
